### ISSUE TITLE
Test result output directory ?

### ISSUE THREAD

**Issue by m0ty** [dazfuller/PyUnitTestTask#5]
Is there a way to change where TEST-*.xml test results are stored ?

Why doesn't it make use of Common.TestResultsDirectory (Agent\\_work\1\TestResults) anyway ?

**Comment by dazfuller** [comment]
Because at the time I wrote it that wasn't a thing, the task needs an uplift to bring it in-line with changes that have happened since the original implementation.

At the moment there isn't a way to change where the test results are stored
